export const DATA_CONTRACT_VERSION = "2025-01-01";

export const MIN_SUPPORTED_CLIENT_VERSION = "2025-01-01";

export const MIN_SUPPORTED_SERVER_VERSION = "2025-01-01";

export const VERSION_METADATA = {
  contract: DATA_CONTRACT_VERSION,
  client: MIN_SUPPORTED_CLIENT_VERSION,
  server: MIN_SUPPORTED_SERVER_VERSION,
} as const;
